# Dependencies
markdown:         redcarpet
highlighter:      true

# Permalinks
permalink:        pretty

# Setup
title:            'Ivan Prisyazhniy'
tagline:          '<a href="https://twitter.com/JohnKoepi" target="_blank">@JohnKoepi</a> backend system engineer'
description:      'Made by <a href="https://twitter.com/JohnKoepi" target="_blank">@JohnKoepi</a>.'
Url:              http://sitano.github.io
baseurl:          '/'
paginate:         5

author:
  name:           'Ivan Prisyazhniy'
  url:            https://twitter.com/JohnKoepi

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/sitano
