# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            '@JohnKoepi'
tagline:          'backend system engineer'
description:      'Made by <a href="https://twitter.com/JohnKoepi" target="_blank">@JohnKoepi</a>.'
url:              http://sitano.github.io
baseurl:          '/'
paginate:         5

author:
  name:           'Ivan Prisyazhnyy'
  url:            https://twitter.com/JohnKoepi

analytics:
  provider: google
  google:
    tracking_id: 'UA-53659396-1'

comments:
  provider: disqus
  disqus:
    short_name: 'sitanogithubio'

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/sitano
